#line 1 "c:\\Users\\LiuZeshu\\Desktop\\esp32_keyboard\\v0.0.0\\poker_keyboard\\Layout.h"
#ifndef LAYOUT_H
#define LAYOUT_H

#include <BleKeyboard.h>
#include "poker_keyboard.h"

#define KEY_FN 0
#define KEY_PN 0

uint8_t LayOut[number_out][number_in] = {
    {KEY_I,KEY_8,KEY_COMMA,KEY_K,KEY_RBRACKET,KEY_EQUAL,0,0}, //0
    {KEY_P,KEY_0,0,KEY_SEMICOLON,KEY_LBRACKET,KEY_SUB,KEY_FSLASH,KEY_SQUOTES}, //1
    {0,0,KEY_RETURN,KEY_BSLASH,KEY_BACKSPACE,KEY_LEFT_CTRL,KEY_FN,KEY_LEFT_ALT}, //2qw
    {KEY_R,KEY_4,KEY_V,KEY_F,KEY_T,KEY_5,KEY_B,KEY_G}, //344rrfvv
    {KEY_Q,KEY_1,KEY_Z,KEY_A,KEY_TAB,KEY_RIGHT_CTRL,KEY_Z,KEY_SQUOTES}, //4II
    {KEY_E,KEY_3,KEY_C,KEY_D,KEY_E,0,KEY_C,KEY_D},//5
    {KEY_O,KEY_9,KEY_FULLSTOP,KEY_L,KEY_LEFT_GUI,0,0,0},
    {KEY_U,KEY_7,KEY_M,KEY_J,KEY_Y,KEY_6,KEY_N,KEY_H},
    {0,0,KEY_PN,KEY_RIGHT_SHIFT,KEY_LEFT_SHIFT,0,KEY_RIGHT_GUI,KEY_RIGHT_SHIFT},//86
    {0,0,0,KEY_BSLASH,KEY_BACKSPACE,0,0,KEY_SPACE},
    {KEY_W,KEY_2,KEY_X,KEY_S,KEY_CAPS_LOCK,KEY_SUB,KEY_X,KEY_S},//10aa
};

#endif